export const groceries = [
  {
    id: "1",
    emoji: "🍎",
    name: "apple",
    amount: 6,
    category: "fruit",
    purchasedDate: "2023-08-24",
    expirationDate: "2023-08-26",
  },
  {
    id: "2",
    emoji: "🍌",
    name: "banana",
    amount: 3,
    category: "fruit",
    purchasedDate: "2023-08-24",
    expirationDate: "2023-08-25",
  },
  {
    id: "3",
    emoji: "🥑",
    name: "avocado",
    amount: 4,
    category: "vegetable",
    purchasedDate: "2023-08-24",
    expirationDate: "2023-08-26",
  },
  //   {
  //     id: "4",
  //     emoji: "🥦",
  //     name: "broccoli",
  //     amount: 1,
  //     category: "vegetable",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-11",
  //   },
  //   {
  //     id: "5",
  //     emoji: "🥩",
  //     name: "beef",
  //     amount: 1,
  //     category: "meat",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-04",
  //   },
  //   {
  //     id: "6",
  //     emoji: "🍗",
  //     name: "chicken wings",
  //     amount: 1,
  //     category: "meat",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-04",
  //   },
  //   {
  //     id: "7",
  //     emoji: "🍩",
  //     name: "donut",
  //     amount: 6,
  //     category: "pastry",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-05",
  //   },
  //   {
  //     id: "8",
  //     emoji: "🥒",
  //     name: "cucumber",
  //     amount: 1,
  //     category: "vegetable",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-05",
  //   },
  //   {
  //     id: "9",
  //     emoji: "🍉",
  //     name: "watermelon",
  //     amount: 1,
  //     category: "fruit",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-04",
  //   },
  //   {
  //     id: "10",
  //     emoji: "🥚",
  //     name: "egg",
  //     amount: 1,
  //     category: "protein food",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-05",
  //   },
  //   {
  //     id: "11",
  //     emoji: "🥓",
  //     name: "bacon",
  //     amount: 3,
  //     category: "meat",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-06",
  //   },
  //   {
  //     id: "12",
  //     emoji: "🫑",
  //     name: "praprika",
  //     amount: 4,
  //     category: "vegetable",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-08",
  //   },
  //   {
  //     id: "13",
  //     emoji: "🍓",
  //     name: "strawberries",
  //     amount: 1,
  //     category: "fruit",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-03",
  //   },
  //   {
  //     id: "14",
  //     emoji: "🍅",
  //     name: "tomato",
  //     amount: 6,
  //     category: "fruit",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-07",
  //   },
  //   {
  //     id: "15",
  //     emoji: "🍱",
  //     name: "sushi box",
  //     amount: 1,
  //     category: "food",
  //     purchasedDate: "2023-07-31",
  //     expirationDate: "2023-08-03",
  //   },
];
